"""Purpose: check that tools/themis.py applies the seven-language readers
the way an owner would notice: long functions refused, generated markers
honoured only when already there, Rust test modules left out of the file
count, per-extension limits that only tighten, exempt files that never
hide a secret, and a baseline that cannot grandfather new code.
Entry points: run by `python3 -m unittest discover -s tests`.
Invariants: every repo is a throwaway under a TemporaryDirectory; the
three tools files are copied in, never this repo's own checkout.
Never change without a decision: which of these behaviours must block.
"""

import importlib.util
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[1]
TOOLS = ("themis.py", "themis_lang.py", "themis_scan.py")
SECRET = "sk-" + "1234567890abcdef1234"

spec = importlib.util.spec_from_file_location("themis_lang", ROOT / "tools" / "themis_lang.py")
lang = importlib.util.module_from_spec(spec)
spec.loader.exec_module(lang)


def ts_function(name, lines, marker=""):
    return marker + "export function %s() {\n%s}\n" % (name, "".join("  step%d();\n" % i for i in range(lines)))


class Repo:
    def __init__(self, tmp, config=None, tools=TOOLS):
        self.path = Path(tmp) / "repo"
        (self.path / "tools").mkdir(parents=True)
        self.git("init", "-q")
        self.git("config", "user.email", "t@example.com")
        self.git("config", "user.name", "t")
        for name in tools:
            (self.path / "tools" / name).write_bytes((ROOT / "tools" / name).read_bytes())
        self.write("themis.json", json.dumps(dict(config or {}, version="v3.2")))
        self.write("main.py", "x = 1\n")

    def git(self, *args):
        return subprocess.run(["git", "-C", str(self.path)] + list(args), check=True,
                              capture_output=True, text=True)

    def write(self, rel, text):
        (self.path / rel).write_text(text, encoding="utf-8")

    def commit(self, message="c"):
        self.git("add", "-A")
        self.git("commit", "-q", "-m", message, "--no-verify")

    def stage(self, *paths):
        self.git("add", *paths)

    def check(self, *args):
        return subprocess.run([sys.executable, str(self.path / "tools" / "themis.py"), "check"] + list(args),
                              cwd=str(self.path), capture_output=True, text=True)

    def staged(self):
        return self.check("--staged")


class WiringTests(unittest.TestCase):
    def repo(self, **kwargs):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        return Repo(tmp.name, **kwargs)

    def test_a_long_typescript_function_is_refused(self):
        repo = self.repo()
        repo.commit()
        repo.write("a.ts", ts_function("big", 120))
        repo.stage("a.ts")
        result = repo.staged()
        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn("function big", result.stdout)

    def test_a_marker_added_in_the_same_commit_does_not_exempt_a_file(self):
        repo = self.repo()
        repo.write("a.ts", "export const a = 1;\n")
        repo.commit()
        repo.write("a.ts", ts_function("big", 120, "// Code generated by hand. DO NOT EDIT.\n"))
        repo.stage("a.ts")
        result = repo.staged()
        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn("not honoured", result.stdout)

    def test_a_token_inside_a_marker_is_never_printed(self):
        repo = self.repo()
        repo.write("a.ts", "// Code generated by hand. DO NOT EDIT.\nexport const a = 1;\n")
        repo.commit()
        repo.write("a.ts", "// Code generated by %s DO NOT EDIT.\nexport const a = 2;\n" % SECRET)
        repo.stage("a.ts")
        result = repo.staged()
        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn("looks like", result.stdout)
        self.assertNotIn(SECRET, result.stdout + result.stderr)

    def test_a_file_that_carried_the_marker_at_head_is_skipped(self):
        repo = self.repo()
        repo.write("a.ts", ts_function("big", 120, "// Code generated by hand. DO NOT EDIT.\n"))
        repo.commit()
        repo.write("a.ts", ts_function("big", 130, "// Code generated by hand. DO NOT EDIT.\n"))
        repo.stage("a.ts")
        result = repo.staged()
        self.assertEqual(result.returncode, 0, result.stdout)
        self.assertIn("generated", result.stdout)

    def test_a_renamed_file_with_a_marker_is_measured(self):
        repo = self.repo()
        repo.write("old.ts", ts_function("big", 120, "// Code generated by hand. DO NOT EDIT.\n"))
        repo.commit()
        repo.git("mv", "old.ts", "new.ts")
        result = repo.staged()
        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn("new.ts", result.stdout)

    def test_rust_test_module_lines_do_not_count_against_the_file(self):
        repo = self.repo()
        repo.commit()
        production = "const A: u32 = 1;\n" * 700
        tests = "mod tests {\n" + "    const B: u32 = 1;\n" * 198 + "}\n"
        for attribute, expected in (("#[cfg(test)]", 0), ("#[cfg(not(test))]", 1)):
            with self.subTest(attribute=attribute):
                repo.write("lib.rs", production + attribute + "\n" + tests)
                repo.stage("lib.rs")
                result = repo.staged()
                self.assertEqual(result.returncode, expected, result.stdout)
                if expected:
                    self.assertIn("over the 800-line limit", result.stdout)

    def test_limits_tighten_and_never_loosen(self):
        for limit, lines, expected in ((50, 60, 1), (500, 120, 1), (500, 60, 0)):
            with self.subTest(limit=limit, lines=lines):
                repo = self.repo(config={"limits": {".ts": {"function": limit}}})
                repo.commit()
                repo.write("a.ts", ts_function("f", lines))
                repo.stage("a.ts")
                self.assertEqual(repo.staged().returncode, expected)

    def test_an_exempt_file_skips_sizes_but_not_the_secret_scan(self):
        repo = self.repo(config={"exempt_files": {"big.ts": "vendored table"}})
        repo.commit()
        repo.write("big.ts", ts_function("big", 120) + 'const key = "%s";\n' % SECRET)
        repo.stage("big.ts")
        result = repo.staged()
        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn("looks like", result.stdout)
        self.assertNotIn("function big", result.stdout)
        self.assertNotIn(SECRET, result.stdout)

    def baseline_case(self, edit_after_base):
        repo = self.repo()
        repo.write("a.ts", ts_function("big", 120))
        repo.commit()
        edit_after_base(repo)
        return repo

    def baseline_entry(self, repo, path, name):
        size = lang.functions((repo.path / path).read_text(encoding="utf-8"), ".ts")[0][name]
        repo.write("themis-baseline.json", json.dumps({"lang": {"functions": {path: {name: size}}}}))
        repo.stage("themis-baseline.json")

    def test_a_baseline_entry_matching_head_is_accepted(self):
        repo = self.baseline_case(lambda r: None)
        self.baseline_entry(repo, "a.ts", "big")
        result = repo.staged()
        self.assertEqual(result.returncode, 0, result.stdout)

    def test_a_baseline_entry_for_a_function_added_now_is_refused(self):
        repo = self.baseline_case(lambda r: (r.write("b.ts", ts_function("fresh", 120)), r.stage("b.ts")))
        self.baseline_entry(repo, "b.ts", "fresh")
        result = repo.staged()
        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn("baseline only goes down", result.stdout)

    def test_a_baseline_entry_larger_than_head_is_refused(self):
        repo = self.baseline_case(lambda r: (r.write("a.ts", ts_function("big", 130)), r.stage("a.ts")))
        self.baseline_entry(repo, "a.ts", "big")
        result = repo.staged()
        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn("baseline only goes down", result.stdout)

    def test_a_missing_sibling_ends_the_run_with_one_line(self):
        repo = self.repo(tools=("themis.py",))
        result = repo.check()
        self.assertEqual(result.returncode, 1)
        self.assertEqual(len(result.stdout.strip().splitlines()), 1, result.stdout)
        self.assertNotIn("Traceback", result.stdout + result.stderr)

    def test_a_run_leaves_no_bytecode_folder_in_the_repo(self):
        repo = self.repo()
        repo.write("a.ts", "export const a = 1;\n")
        repo.stage("a.ts")
        repo.staged()
        repo.check()
        self.assertEqual(list(repo.path.rglob("__pycache__")), [])


if __name__ == "__main__":
    unittest.main()
