"""Purpose: check that themis_lang.py measures function length and reads
comments in the seven brace languages (the scanner loads beside it), and that the five holes a design
review found in the prototype stay closed.
Entry points: run by `python3 -m unittest discover -s tests`.
Invariants: pure strings in, no filesystem or git involved beyond loading
the two tools by path; nothing is written.
Never change without a decision: the measured numbers in LANGUAGES, which
are what an owner would notice changing, and the one-second bound.
"""

import importlib.util
import re
import shutil
import sys
import tempfile
import time
import unittest
from pathlib import Path

sys.dont_write_bytecode = True
TOOLS = Path(__file__).resolve().parents[1] / "tools"


def load(name):
    spec = importlib.util.spec_from_file_location(name, TOOLS / (name + ".py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


lang = load("themis_lang")
themis = load("themis")

RUST = r'''//! Crate docs: dates like 2024-01-31 are examples here.
/// Returns 'a'; the old value is previously stored.
pub fn pick<'a>(x: &'a str) -> &'a str {
    let s = r#"not a { brace "# ;
    let c = '{';
    /* outer /* inner { */ still comment } */
    x
}
impl<T: Clone> Iterator for Wrap<T> {
    type Item = T;
    fn next(&mut self) -> Option<T>
    where T: Default {
        None
    }
}
trait Shape { fn area(&self) -> f64; }
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn it_works() {
        assert_eq!(pick("x"), "x");
    }
}
'''
GO = '''// Code generated by hand for this fixture.
package p

// Server serves.
type Server struct{ n int }

func (s *Server) Handle(m map[string]interface{}) error {
	x := `raw { brace`
	r := '{'
	go func() {
		_ = x
	}()
	_ = r
	return nil
}

func Free[T any](v T) interface{} {
	return v
}
'''
SWIFT = r'''/// Doc: previously cached.
struct V: View {
    let raw = #"a "quoted" { brace"#
    let multi = """
        has \(f("}")) inside
        """
    var body: some View {
        Text("x")
    }
    /* outer /* nested */ { */
    init(x: Int) {
        print("{")
    }
    func `default`() -> Int { 1 }
    func make<T>(_ t: T) -> T
        where T: Equatable {
        return t
    }
}
protocol P {
    func req() -> Int
    var count: Int { get }
}
extension V {
    deinit {
    }
}
'''
TS = r'''/** JSDoc block, previously documented. */
export function parse(s: string): { ok: boolean } {
  const re = /[{"]/g;
  const t = `a ${s.replace(/}/g, "")} {`;
  return { ok: re.test(t) };
}
export const handler = async (e: { id: string }): Promise<void> => {
  items.forEach((x) => {
    console.log(x);
  });
};
class Store {
  private cache = new Map();
  get size(): number {
    return this.cache.size;
  }
  async load(id: string) {
    if (id) {
      return 1;
    }
  }
}
describe("suite", () => {
  it("works", () => {});
});
const App = () => <p>Don't {"break"}</p>;
'''
JAVA = r'''/** Javadoc. */
public class A extends B {
    @Override
    public String toString() {
        String s = "}";
        char c = '{';
        String block = """
            { not code
            """;
        return s + c;
    }
    A(int x) throws IOException {
        Runnable r = new Runnable() {
            public void run() { }
        };
        list.forEach(v -> {
            use(v);
        });
    }
}
'''
KOTLIN = r'''/** KDoc. */
class Repo(private val api: Api) {
    fun `doesn't crash on empty`() {
        val s = "${api.name { "}" }}"
        val raw = """ { $s """
    }
    fun one() = api.call {
        it
    }
    /* outer /* nested */ { */
    companion object {
        fun create(): Repo {
            return Repo(Api())
        }
    }
}
'''
CSHARP = r'''/// <summary>Doc.</summary>
public class C : Base {
    public C(int x) : base(x) {
        var v = @"path\{dir}""";
        var i = $"{x} {{literal}}";
        var r = """
            { raw "quotes" }
            """;
    }
    public async Task<int> RunAsync<T>(T t) where T : class {
        return await Task.FromResult(1);
    }
    public int Prop { get { return 1; } }
}
'''
# source, extension, measured sizes. The TS and Kotlin entries include the
# anonymous blocks outside any function: the `it` callback and the describe
# wrapper's own two lines, and `fun one() = api.call {`.
LANGUAGES = {
    "rust": (RUST, ".rs", {"pick": 6, "Wrap.next": 4, "tests.it_works": 3}),
    "go": (GO, ".go", {"Server.Handle": 9, "Free": 3}),
    "swift": (SWIFT, ".swift", {"V.body": 3, "V.init": 3, "V.`default`": 1, "V.make": 4,
                                "V.deinit": 2, "P.count": 1}),
    "ts": (TS, ".ts", {"parse": 5, "handler": 5, "Store.size": 3, "Store.load": 5,
                       "<anonymous>#1": 1, "<anonymous>#2": 2}),
    "java": (JAVA, ".java", {"A.toString": 8, "A.A": 8, "A.A.Runnable.run": 1}),
    "kotlin": (KOTLIN, ".kt", {"Repo.`doesn't crash on empty`": 4, "Repo.one": 3,
                               "Repo.companion object.create": 3}),
    "csharp": (CSHARP, ".cs", {"C.C": 7, "C.RunAsync": 3}),
}
BODY = "\n".join("    step%d()" % i for i in range(120))


class LanguageTests(unittest.TestCase):
    def check(self, name):
        source, ext, expected = LANGUAGES[name]
        sizes, notes = lang.functions(source, ext)
        self.assertEqual(sizes, expected)
        self.assertEqual(notes, [])

    def test_rust_sizes_comments_and_test_module(self):
        self.check("rust")
        source, ext, _ = LANGUAGES["rust"]
        self.assertEqual(lang.test_spans(source, ext), [(17, 24)])
        self.assertEqual(sorted(lang.comments(source, ext)), [1, 2, 6])

    def test_go_sizes(self):
        self.check("go")

    def test_swift_sizes(self):
        self.check("swift")

    def test_typescript_sizes(self):
        self.check("ts")

    def test_java_sizes(self):
        self.check("java")

    def test_kotlin_sizes(self):
        self.check("kotlin")

    def test_csharp_sizes(self):
        self.check("csharp")

    def test_other_languages_have_no_test_spans(self):
        self.assertEqual(lang.test_spans(GO, ".go"), [])


class ReviewHoleTests(unittest.TestCase):
    def test_a_closure_outside_any_function_is_measured(self):
        cases = [
            (".kt", "fun big() = run {\n%s\n}\n" % BODY, "big"),
            (".go", "package p\nvar H = func() {\n%s\n}\n" % BODY, "H"),
            (".swift", "struct S {\n  let cb: () -> Void = {\n%s\n  }\n}\n" % BODY, "S.cb"),
            (".ts", "app.get('/', (req, res) => {\n%s\n})\n" % BODY, "<anonymous>#1"),
        ]
        for ext, source, key in cases:
            with self.subTest(ext=ext):
                self.assertGreater(lang.functions(source, ext)[0].get(key, 0), 100)

    def test_a_long_function_in_an_awkward_header_is_still_measured(self):
        cases = [
            (".cs", "class C {\n  public T Run<T, U>(T t) where T : struct where U : class {\n%s\n  }\n}\n", "C.Run"),
            (".ts", "class S {\n  async *gen<T extends {a: string}>(x: T): AsyncGenerator<T> {\n%s\n  }\n}\n", "S.gen"),
            (".ts", "function f<T extends {a: string}>(x: T) {\n%s\n}\n", "f"),
            (".java", "record P(int x) {\n  P {\n%s\n  }\n}\n", "P.P"),
        ]
        for ext, template, key in cases:
            with self.subTest(key=key):
                sizes, _ = lang.functions(template % BODY, ext)
                self.assertGreater(sizes.get(key, 0), 100)

    def test_rust_array_types_in_signatures_are_measured(self):
        cases = ["fn key() -> [u8; 32] {\n%s\n}\n", "fn key(p: [bool; 2]) {\n%s\n}\n",
                 "fn key() -> Result<Zeroizing<[u8; 32]>, E> {\n%s\n}\n",
                 "impl S {\n    pub fn key(&self) -> [u8; 32] {\n%s\n    }\n}\n"]
        for template in cases:
            with self.subTest(template=template.split("{")[0]):
                sizes, notes = lang.functions(template % BODY, ".rs")
                self.assertGreater(max(sizes.values(), default=0), 100)
                self.assertEqual(notes, [])

    def test_a_long_block_with_a_function_keyword_fails_closed(self):
        odd = "fn odd(x: (u8; 3)) {\n%s\n}\n" % BODY
        sizes, notes = lang.functions(odd, ".rs")
        self.assertGreater(sizes.get("<unmeasured>#1", 0), 100)
        self.assertEqual(len(notes), 1)

    def test_a_long_unrecognised_block_is_noted_not_silent(self):
        long_table = "const table = {\n%s\n}\n" % "\n".join("  k%d: %d," % (i, i) for i in range(150))
        sizes, notes = lang.functions(long_table, ".ts")
        self.assertEqual(sizes, {})
        self.assertEqual(len(notes), 1)
        self.assertIn("not recognised as a function", notes[0])
        short = "const table = {\n%s\n}\n" % "\n".join("  k%d: %d," % (i, i) for i in range(50))
        self.assertEqual(lang.functions(short, ".ts"), ({}, []))

    def test_a_wrapper_of_short_callbacks_is_not_one_long_function(self):
        tests = "".join('  it("t%d", () => {\n    a()\n    b()\n  })\n' % i for i in range(40))
        sizes, _ = lang.functions('describe("suite", () => {\n%s})\n' % tests, ".ts")
        self.assertEqual(len(sizes), 41)
        self.assertLess(max(sizes.values()), 10)

    def test_one_long_anonymous_callback_is_measured_in_full(self):
        source = "app.get('/', (req, res) => {\n%s\n})\n" % BODY
        self.assertEqual(lang.functions(source, ".ts")[0], {"<anonymous>#1": 122})

    def test_a_closure_inside_a_function_counts_toward_it(self):
        source = "func F() {\n  go func() {\n%s\n  }()\n}\n" % BODY
        sizes, _ = lang.functions(source, ".go")
        self.assertEqual(list(sizes), ["F"])

    def test_a_missing_brace_is_reported_not_silent(self):
        sizes, notes = lang.functions("class A {\n  m() {\n    return 1\n  }\n", ".ts")
        self.assertEqual(sizes, {"A.m": 3})
        self.assertTrue(any("unclosed brace" in n for n in notes))

    def test_statements_ending_at_a_newline_do_not_hide_the_next_method(self):
        cases = [
            (".ts", "class A {\n  x = foo(1)\n  m() {\n    return 1\n  }\n}\n", "A.m"),
            (".kt", "class A {\n  val x = foo(1)\n  fun m() {\n  }\n}\n", "A.m"),
            (".swift", "struct A {\n  let x = foo(1)\n  func m() {\n  }\n}\n", "A.m"),
            (".go", "type S struct {\n a int\n}\nvar x = foo(1)\nfunc (s S) m() {\n}\n", "S.m"),
        ]
        for ext, source, key in cases:
            with self.subTest(ext=ext):
                self.assertIn(key, lang.functions(source, ext)[0])

    def test_decorated_lines_are_measured_in_linear_time(self):
        source = "class A {\n" + "  @x(1) a: (b)\n" * 1000 + "  m() {\n    return 1\n  }\n}\n"
        start = time.time()
        sizes, _ = lang.functions(source, ".ts")
        self.assertLess(time.time() - start, 1.0)
        self.assertEqual(sizes, {"A.m": 3})

    def test_absurd_nesting_gives_a_note_not_a_crash(self):
        sizes, notes = lang.functions("`${" * 3000, ".ts")
        self.assertEqual(sizes, {})
        self.assertTrue(notes)
        lang.comments("`${" * 3000, ".ts")

    def test_only_an_exact_cfg_test_is_a_test_module(self):
        prod = '#[cfg(not(test))]\nmod prod {\n}\n#[cfg(any(test, feature = "x"))]\nmod m {\n}\n'
        self.assertEqual(lang.test_spans(prod, ".rs"), [])
        exact = "fn a() {}\n#[cfg(test)]\n#[allow(dead_code)]\npub mod t {\n}\n"
        self.assertEqual(lang.test_spans(exact, ".rs"), [(2, 5)])


class LoadingTests(unittest.TestCase):
    def test_loading_by_path_leaves_no_bytecode_folder(self):
        with tempfile.TemporaryDirectory() as tmp:
            for name in ("themis_lang.py", "themis_scan.py"):
                shutil.copy(TOOLS / name, tmp)
            spec = importlib.util.spec_from_file_location("copy_lang", Path(tmp) / "themis_lang.py")
            spec.loader.exec_module(importlib.util.module_from_spec(spec))
            self.assertEqual(sorted(p.name for p in Path(tmp).iterdir()),
                             ["themis_lang.py", "themis_scan.py"])

    def test_a_missing_sibling_is_one_clear_error(self):
        with tempfile.TemporaryDirectory() as tmp:
            shutil.copy(TOOLS / "themis_lang.py", tmp)
            spec = importlib.util.spec_from_file_location("lonely", Path(tmp) / "themis_lang.py")
            with self.assertRaisesRegex(ImportError, "themis_scan.py"):
                spec.loader.exec_module(importlib.util.module_from_spec(spec))


class HistoryTests(unittest.TestCase):
    PATTERN = re.compile(themis.HISTORY_WORDS.pattern + "|forbidden", re.IGNORECASE)

    FLAGGED = [
        "it used to leak", "that used to be slow", "we didn't use to check",
        "Previously, this returned X", "was previously hard-coded",
        "fixed on 2024-01-31", "asked by the reviewer", "after the review of the change",
        "DO NOT MERGE", "written this session", "a forbidden word",
    ]
    NOT_FLAGGED = [
        "Sender used to forward", "is used to build the index", "previously set by the caller",
        "previously stored here", 'the string "used to leak" is quoted',
        "the date `2024-01-31` is an example", "see https://example.org/2024-01-31/notes",
    ]

    def hits(self, lines):
        return lang.history_hits({n: t for n, t in enumerate(lines, 1)}, self.PATTERN)

    def test_flagged_and_unflagged_wording(self):
        for text in self.FLAGGED:
            with self.subTest(text=text):
                self.assertEqual(len(self.hits([text])), 1)
        for text in self.NOT_FLAGGED:
            with self.subTest(text=text):
                self.assertEqual(self.hits([text]), [])

    def test_fenced_code_is_skipped_and_a_gap_ends_the_fence(self):
        self.assertEqual(self.hits(["```", "it used to leak", "```", "it used to leak"]), [(4, "used to")])
        found = {1: "```", 5: "it used to leak"}
        self.assertEqual(lang.history_hits(found, self.PATTERN), [(5, "used to")])


class GeneratedAndLimitTests(unittest.TestCase):
    def test_generated_markers_in_leading_comments_only(self):
        marked = [
            "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage p\n",
            "/* @generated SignedSource<<abc>> */\nconst a = 1;\n",
            "// Generated by the protocol buffer compiler.  DO NOT EDIT!\n",
            "/// <auto-generated>\n/// tool\n/// </auto-generated>\nclass C {}\n",
        ]
        for text in marked:
            with self.subTest(text=text[:30]):
                self.assertIsNotNone(lang.generated(text))
        self.assertIsNone(lang.generated("fn a() {}\n// @generated later\n"))
        self.assertIsNone(lang.generated("// plain header\n" + "// x\n" * 12 + "// @generated\n"))

    def test_limits_only_tighten(self):
        config = {".ts": {"file": 500}, ".rs": {"function": 80}, ".go": {"file": 9000, "function": "x"},
                  ".kt": {"file": True}, ".cs": 7}
        self.assertEqual(lang.clamp_limits(config, ".ts", 800, 100), (500, 100))
        self.assertEqual(lang.clamp_limits(config, ".rs", 800, 100), (800, 80))
        self.assertEqual(lang.clamp_limits(config, ".go", 800, 100), (800, 100))
        self.assertEqual(lang.clamp_limits(config, ".kt", 800, 100), (800, 100))
        self.assertEqual(lang.clamp_limits(config, ".cs", 800, 100), (800, 100))
        self.assertEqual(lang.clamp_limits(None, ".ts", 800, 100), (800, 100))


if __name__ == "__main__":
    unittest.main()
